# Lesson 0 - Fundamentals

In [52]:
import torch

In [2]:
torch.__version__

'2.2.1+cu121'

## Intro to Tensors

### Scalar


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Returning the values inside the scalar tensor as python int
scalar.item()

7

### Vectors

In [6]:

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
#Item only works on scalars
vector.item()

RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

### Matrix

In [9]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [10]:
matrix.ndim

2

#### Note: No. of square brackets = ndim value

In [11]:
matrix[0]

tensor([1, 2])

In [12]:
matrix[0,1]

tensor(2)

In [13]:
matrix.shape

torch.Size([2, 2])

### TENSOR

In [14]:
tensor = torch.tensor([[[1,2],[2,3]],[[4,5],[6,7]]])
tensor

tensor([[[1, 2],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([2, 2, 2])

In [17]:
tensor[0]

tensor([[1, 2],
        [2, 3]])

In [18]:
tensor[0,0]

tensor([1, 2])

In [19]:
tensor[0,0,0]

tensor(1)

### Random Tensors


In [20]:
#Creating a tensor of specified shape
RT = torch.rand(3,4)
RT

tensor([[0.7435, 0.5317, 0.4289, 0.4481],
        [0.6896, 0.5323, 0.8515, 0.9823],
        [0.5043, 0.2120, 0.9081, 0.4870]])

In [21]:
RT.ndim

2

In [22]:
#Creating a tensor of specified image size
ImageRT = torch.rand(size=(3,224,224))
#224*224 image size with 3 color channels (RGB)
ImageRT.shape,ImageRT.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [23]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
RT * zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones =torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of tensors 

In [26]:
torch.arange(1,3)
#to create a tensor of 1 row from start value to end value 

tensor([1, 2])

In [27]:
step = torch.arange(0,100,step = 10)
step

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Tensors like

In [28]:
one_step = torch.ones_like(step)
one_step
#_like Creates tensors which match the shape of ( parameter )

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

In [29]:
datatype = torch.tensor ([1,2,3], dtype = None)
datatype.dtype #Default dtype 

torch.int64

In [30]:
#converting into different data type
float_32 = datatype.type(torch.float32)
float_32

tensor([1., 2., 3.])

In [31]:
#Default float data type
datatype_f = torch.tensor ([1.,2.,3.])
datatype_f.dtype

torch.float32

## Crucial error in PyTorch
Operation of different datatypes might run into errors

In [32]:
float_64 = float_32.type(torch.double)
float_64

tensor([1., 2., 3.], dtype=torch.float64)

In [33]:
float_32 * datatype

tensor([1., 4., 9.])

In [34]:
#Default device that a tensor is stored in
#Tensors in different devices can result in error
tensor.device

device(type='cpu')

In [35]:
#Tensors with different shapes can result in errors
float_64 *RT

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

## Tensor Operations

In [36]:
#Matrix Multiplication (dot product)
print(datatype)
torch.matmul (datatype, datatype)
#torch.mm shortform

tensor([1, 2, 3])


tensor(14)

In [37]:
%%time
datatype * datatype #Element wise multiplication

CPU times: total: 0 ns
Wall time: 0 ns


tensor([1, 4, 9])

### matmul doesn't work on matrices of different shapes
to operate, we need to transpose one of the matrices

In [38]:
tensor_A = torch.tensor([[1,2],
            [3,4],
            [5,6]])
tensor_B = torch.tensor([[1,2],
            [3,4],
            [5,6]])
print(tensor_A.shape,tensor_B.shape)

torch.Size([3, 2]) torch.Size([3, 2])


In [39]:
torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [40]:
tensor_B.T
#Transpose operation

tensor([[1, 3, 5],
        [2, 4, 6]])

In [41]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

### Finding min,max,mean,sum etc. (Aggregation)
Aggregation -> Large numbers to small numbers

In [42]:
X = torch.arange(2,20,step=2)
X

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
print( "min:",torch.min(X))
print("max:",torch.max(X))

min: tensor(2)
max: tensor(18)


In [44]:
torch.mean(X)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [45]:
X_f32=X.type(torch.float32) #Changing dtype
print(f"mean: {torch.mean(X_f32)}") 

mean: 10.0


In [46]:
torch.sum(X)

tensor(90)

### Finding position min,max

In [47]:
torch.argmin(X) #Returns index of minimum value

tensor(0)

In [48]:
torch.argmax(X)

tensor(8)

## Reshaping, stacking, Squeezing, Views

### Reshape

In [90]:
import torch

x = torch.rand(1,8)
x

tensor([[0.8867, 0.9247, 0.5803, 0.7408, 0.5056, 0.3079, 0.6024, 0.4905]])

In [91]:
#changing tensor dimensions, reshape needs to fit all elements of original tensor
x_reshaped = x.reshape (8,1)
x_reshaped

tensor([[0.8867],
        [0.9247],
        [0.5803],
        [0.7408],
        [0.5056],
        [0.3079],
        [0.6024],
        [0.4905]])

In [92]:
#Reshape is sometimes same memory but sometimes a copy and you cannot depend on it (depends upon contiguous and "strides")
#If you want same memory explicitly use view
x_reshaped[0]=0
print(x_reshaped)
print(x)

tensor([[0.0000],
        [0.9247],
        [0.5803],
        [0.7408],
        [0.5056],
        [0.3079],
        [0.6024],
        [0.4905]])
tensor([[0.0000, 0.9247, 0.5803, 0.7408, 0.5056, 0.3079, 0.6024, 0.4905]])


### View

In [80]:
#Same as reshape, but uses same memory as original tensor (Pointer)
z= x.view(2,4)
z

tensor([[0.6851, 0.8995, 0.3796, 0.5805],
        [0.2926, 0.0047, 0.9823, 0.3803]])

In [82]:
z[0,0] = 0
#Changing value in z results in change of x as well
print(x)
print(z)

tensor([[0.0000, 0.8995, 0.3796, 0.5805, 0.2926, 0.0047, 0.9823, 0.3803]])
tensor([[0.0000, 0.8995, 0.3796, 0.5805],
        [0.2926, 0.0047, 0.9823, 0.3803]])


tensor([[0.0000],
        [0.8995],
        [0.3796],
        [0.5805],
        [0.2926],
        [0.0047],
        [0.9823],
        [0.3803]])
tensor([[0.0000, 0.8995, 0.3796, 0.5805, 0.2926, 0.0047, 0.9823, 0.3803]])


### Stack

In [99]:
x = torch.tensor([1,2,3,4,5])
x_stacked = torch.stack([x,x,x,x],dim=0) #default 0
x_stacked

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [104]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5]])

### Squeeze and Unsqueeze

In [124]:
#Fix dimensions mismatch
x = torch.zeros(1,2,1,2)
print(x,x.size())

tensor([[[[0., 0.]],

         [[0., 0.]]]]) torch.Size([1, 2, 1, 2])


In [140]:
#By default, removes any dim of 1 from entire tensor
#If dim is specified, then removes the specific index of dim if it has dim 1 in torch.Size()
y = torch.squeeze(x)
print(y,y.size())

tensor([[0., 0.],
        [0., 0.]]) torch.Size([2, 2])


In [142]:
y = torch.squeeze(x,dim = 0) #Removing 1 dim from 0 index in torch.size of x
print(y,y.size())

tensor([[[0., 0.]],

        [[0., 0.]]]) torch.Size([2, 1, 2])


In [136]:
#Add dim 1 in specified size index
z = torch.unsqueeze(y,dim=0)
print(z,z.size())

tensor([[[0., 0.],
         [0., 0.]]]) torch.Size([1, 2, 2])


### Permute

In [147]:
# Common to re-arrange image data
x = torch.rand(224,224,3) #size implicit call [height,width,color_channel]

In [152]:
x_permute = x.permute(2,0,1) #shifting axis
print(f"Previous shape: {x.shape}")
print(f"Previous shape: {x_permute.shape}")

Previous shape: torch.Size([224, 224, 3])
Previous shape: torch.Size([3, 224, 224])


In [160]:
x[0,0,0] = 999
x_permute[0,0,0]
#They share the same memory

tensor(999.)

 ## Reproducability
 Pseudo-randomness for non-deterministic functions

In [3]:
import torch
#Setting manual seed only works for the successive non-deterministic code
torch.manual_seed(42)
A=torch.rand(3,3)
B=torch.rand(3,3)
print(A)
print(B)


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


#### Check https://pytorch.org/docs/stable/notes/randomness.html for more info